apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: zabbix-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: zabbix-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: zabbix-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-mysql
  labels:
    app: zabbix-mysql
spec:
  selector:
    matchLabels:
      app: zabbix-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zabbix-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: 500m
            memory: "512Mi"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: root-password
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
