apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
spec:
  ports:
  - port: 10051
  selector:
    app: zabbix-server
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-server
spec:
  selector:
    matchLabels:
      app: zabbix-server
  replicas: 2
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - image: docker.io/zabbix/zabbix-server-mysql:alpine-3.4.13
        name: zabbix-server
        env:
          # Use secret in real usage
        - name: DB_SERVER_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: root-password
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        ports:
        - containerPort: 10051
          name: zabbix-server
