apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: zabbix-web
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zabbix-web
spec:
  selector:
    matchLabels:
      app: zabbix-web
  replicas: 2
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - image: docker.io/zabbix/zabbix-web-nginx-mysql:alpine-3.4.14
        name: zabbix-web
        env:
          # Use secret in real usage
        - name: DB_SERVER_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: root-password
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        livenessProbe:
          # an http probe
          httpGet:
            path: /
            port: 80
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 20
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          name: zabbix-web
